export const projects = [
  {
    id: 4,
    project: 'PortfolioCsT1',
    developed_in2: 'JavaScrip',
    description: 'Basic Portfolio Website that built with HTML, CSS and JavaScript, and shows two pages as a sample if more needed.',
    Repo: 'https://github.com/Have-Samuel/PortfolioCsT1',
    Pair_Programmed: 'No',
    API: 'No',
  },
  {
    id: 2,
    project: 'BudgetApp',
    developed_in2: 'Ruby',
    description: 'A simple, user-friendly mobile iphone web application that helps you manage your funds moneybag',
    repo: 'https://github.com/Have-Samuel/BudgetApp',
    Pair_Programmed: 'Yes',
    API: 'No',
  },
  {
    id: 3,
    project: 'Zuku-apartment',
    developed_in2: 'JS, RoR',
    description: 'Zuku Apartments is a Web application that allows users to sign in and make reservations for an apartment of their choice.',
    Repo: 'https://github.com/Have-Samuel/Zuku-apartment',
    Pair_Programmed: 'Yes',
    API: 'Yes',
  },
  {
    id: 1,
    project: 'Animal Reserve',
    developed_in2: 'Reactjs',
    description: 'In this project I built a mobile web application to check a list of animals making use of React and Redux.',
    Repo: 'https://github.com/Have-Samuel/animal-reserve',
    Pair_Programmed: 'No',
    API: 'Yes',
  },
  {
    id: 5,
    project: 'MM-fullWebsite',
    developed_in2: 'Reactjs',
    description: 'A website for all fans of mathematics.',
    Repo: 'https://github.com/Have-Samuel/MM-fullWebsite',
    Pair_Programmed: 'No',
    API: 'No',
  },
  {
    id: 6,
    project: 'todoLT',
    developed_in2: 'Javascript',
    description: 'The ToDo list project, we applied the webpack and testing of the app, to see how where and solve an testing errors.',
    Repo: 'https://github.com/Have-Samuel/todoLT',
    Pair_Programmed: '',
    API: 'No',
  },
];
