export const projects = [
  {
    id: 4,
    project: '',
    developed_in2: '',
    description: '',
    Repo: '',
    Pair_Programmed: '',
    API: '',
  },
  {
    id: 2,
    project: '',
    developed_in2: '',
    description: '',
    repo: '',
    Pair_Programmed: '',
    API: '',
  },
  {
    id: 3,
    project: '',
    developed_in2: '',
    description: '',
    Repo: '',
    Pair_Programmed: '',
    API: '',
  },
  {
    id: 1,
    project: '',
    developed_in2: '',
    description: '',
    Repo: '',
    Pair_Programmed: '',
    API: '',
  },
  {
    id: 5,
    project: '',
    developed_in2: '',
    description: '',
    Repo: '',
    Pair_Programmed: '',
    API: '',
  },
  {
    id: 6,
    project: '',
    developed_in2: '',
    description: '',
    Repo: '',
    Pair_Programmed: '',
    API: '',
  },
];
