/* eslint-disable import/prefer-default-export */
export const projects = [
  {
    id: 4,
    project: 'PortfolioCsT1',
    developed_in: 'JavaScript',
    developed_in2: 'N/A',
    img: '../../../PortfolioCST1.png',
    description: 'Basic Portfolio Website that built with HTML, CSS and JavaScript, and shows two pages as a sample if more needed.',
    Repo: 'https://have-samuel.github.io/PortfolioCsT1/',
    Pair_Programmed: 'No',
    API: 'No',
  },
  {
    id: 2,
    project: 'BudgetApp',
    developed_in: 'Ruby on Rails',
    developed_in2: 'N/A',
    img: '',
    description: 'A simple, user-friendly mobile iphone web application that helps you manage your funds moneybag',
    Repo: 'https://afternoon-tor-26481.herokuapp.com/splash',
    Pair_Programmed: 'Yes',
    API: 'No',
  },
  {
    id: 3,
    project: 'Zuku-apartment',
    developed_in: 'Javascript',
    developed_in2: 'Ruby on Rails',
    img: '',
    description: 'Zuku Apartments is a Web application that allows users to sign in and make reservations for an apartment of their choice.',
    Repo: 'https://zuku-apartments-frontend.vercel.app/',
    Pair_Programmed: 'Yes',
    API: 'Yes',
  },
  {
    id: 1,
    project: 'Animal Reserve',
    developed_in: 'Javascript',
    developed_in2: 'N/A',
    img: '',
    description: 'In this project I built a mobile web application to check a list of animals making use of React and Redux.',
    Repo: 'https://animal-world-bdda73.netlify.app/',
    Pair_Programmed: 'No',
    API: 'Yes',
  },
  {
    id: 5,
    project: 'MM-fullWebsite',
    developed_in: 'Javascript',
    developed_in2: 'N/A',
    img: '',
    description: 'A website for all fans of mathematics.',
    Repo: 'https://math256.herokuapp.com/',
    Pair_Programmed: 'No',
    API: 'No',
  },
  {
    id: 6,
    project: 'todoLT',
    developed_in: 'Javascript',
    developed_in2: 'N/A',
    img: '',
    description: 'The ToDo list project, we applied the webpack and testing of the app, to see how where and solve an testing errors.',
    Repo: 'https://react-set-up.netlify.app/',
    Pair_Programmed: 'Yes',
    API: 'No',
  },
];
